---
abstract: 'Two letter codes for state identification in the United States and vice versa.'
author:
  - 'Mike Accardo'
build_requires:
  Test: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Locale-US
no_index:
  directory:
    - t
    - inc
requires:
  Data::Dumper: '0'
  Data::Section::Simple: '0'
version: '3.04'
